import '../../../svg/emoji/vomiting.svg'
import '../../../svg/emoji/smirking.svg'
import '../../../svg/emoji/surprised.svg'
import '../../../svg/emoji/unamused.svg'
import '../../../svg/emoji/zombie.svg'
import '../../../svg/emoji/tired.svg'
import '../../../svg/emoji/tongue.svg'
import '../../../svg/emoji/wink.svg'
